name: 'Bors Labeller'
description: 'Labels PRs that have been sent to bors'
author: 'astronouth7303'
inputs: 
  foo:
    description: 'bar'
    default: '-'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.foo }}
